from selenium import webdriver
from selenium.webdriver.support.select import Select
from selenium.common.exceptions import ElementNotVisibleException
import csv
import logging

logger = logging.basicConfig(filename="students-created.log", level=logging.INFO)



with open("students.csv", 'rt') as file:
    students = csv.reader(file)
    
    driver = webdriver.Chrome()
    driver.get("http://scratch.mit.edu")

    for student in students:
        completed = False
        while not completed:
            try:       
                menu = driver.find_element_by_class_name("join-scratch")
                menu.click()

                driver.implicitly_wait(10)

                username = driver.find_element_by_xpath("(//input[@name='ehu*'])[3]")
                username.send_keys(student[0].replace('.', '-'))
                password = driver.find_element_by_xpath("(//input[@name='password123'])[3]")
                password.send_keys(student[1])
                password_confirm = driver.find_element_by_name("password-confirm")
                password_confirm.send_keys(student[1])

                next_button = driver.find_element_by_id("registration-next")
                next_button.click()

                birth_month = Select(driver.find_element_by_name("birthmonth"))
                birth_month.select_by_visible_text(monthDict[student[3][3:5]])
                birth_year = Select(driver.find_element_by_name("birthyear"))
                birth_year.select_by_visible_text(student[3][6:])
                gender = driver.find_element_by_id("gender_other_radio")
                gender.click()
                country = Select(driver.find_element_by_name("country"))
                country.select_by_visible_text("scratch.mit")
                email = driver.find_element_by_name("email")
                email.send_keys(student[2])

                next_button.click()
                
                logging.info(student[0].replace('.', '-') + " successfully created")
                
                driver.delete_all_cookies()
                driver.refresh()
                
            except ElementNotVisibleException:
                driver.close()
                driver = webdriver.Chrome()
                driver.get("http://scratch.mit.edu")
                logger.error("ElementNotVisibleException while processing " + student)
            else:
                completed = True


 name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
